apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-login-api
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: 02-Tutorial-Application/deployment
    repoURL: https://github.com/techwithadedayo/kubernetes-tutorial.git
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
